// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Aspire.MySQLSample.MigrationEntry.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Aspire.MySQLSample.MigrationEntry.Entities.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("users");

            entity.HasIndex(e => e.Username, "ix_users_username").IsUnique();

            entity.Property(e => e.Id)
                .HasMaxLength(16)
                .HasComment("識別碼")
                .HasColumnName("id")
				.UseCollation("utf8mb4_0900_ai_ci");
			entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("創建時間")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .HasComment("密碼")
                .HasColumnName("password")
				.UseCollation("utf8mb4_bin");
			entity.Property(e => e.State)
                .HasComment("狀態")
                .HasColumnName("state");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("更新時間")
                .HasColumnType("timestamp")
                .HasColumnName("update_at");
            entity.Property(e => e.Username)
                .HasMaxLength(32)
                .HasComment("用戶名")
                .HasColumnName("username")
				.UseCollation("utf8mb4_0900_ai_ci");

			OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
